name: Blog Deployment

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build and deploy
    # env:
    #   SECRET: 
    #   USER_NAME: addhome2001
    #   USER_EMAIL: addhome2001@gmail.com
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.20.1]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Setup github and SSH key
      env:
        DEPLOY_PRI_KEY: ${{ secrets.DEPLOY_PRI }}
      run: |
        mkdir -p ~/.ssh/
        echo "$DEPLOY_PRI_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.email "addhome2001@gmail.com"
        git config --global user.name "addhome2001"
    - name: Deployment
      run: |
        yarn deploy
        echo Deploy blog successfully 👻
      
